// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9N_AI5xPzff_GkWpKc3VtN6p6eKcOig',
    appId: '1:814069611978:web:0f37c172be68fe83336333',
    messagingSenderId: '814069611978',
    projectId: 'hospital-f7629',
    authDomain: 'hospital-f7629.firebaseapp.com',
    storageBucket: 'hospital-f7629.appspot.com',
    measurementId: 'G-39G54KYSQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dgXTtR09k_uiKrKo3pdYURE7ngiElI4',
    appId: '1:814069611978:android:8d7d6bc4620bbfc8336333',
    messagingSenderId: '814069611978',
    projectId: 'hospital-f7629',
    storageBucket: 'hospital-f7629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5UO3Ztfn_VPt_VKJRtcVAhZlUnMAbyNA',
    appId: '1:814069611978:ios:75d83c2e4a9ca246336333',
    messagingSenderId: '814069611978',
    projectId: 'hospital-f7629',
    storageBucket: 'hospital-f7629.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5UO3Ztfn_VPt_VKJRtcVAhZlUnMAbyNA',
    appId: '1:814069611978:ios:75d83c2e4a9ca246336333',
    messagingSenderId: '814069611978',
    projectId: 'hospital-f7629',
    storageBucket: 'hospital-f7629.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG9N_AI5xPzff_GkWpKc3VtN6p6eKcOig',
    appId: '1:814069611978:web:5c02c63b5e5b3570336333',
    messagingSenderId: '814069611978',
    projectId: 'hospital-f7629',
    authDomain: 'hospital-f7629.firebaseapp.com',
    storageBucket: 'hospital-f7629.appspot.com',
    measurementId: 'G-5WY2MTH96H',
  );
}
